In [2]:
import pandas as pd

In [2]:
df=pd.read_csv("CO2 Emissions_Canada.csv")
df

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
0,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196
1,ACURA,ILX,COMPACT,2.4,4,M6,Z,11.2,7.7,9.6,29,221
2,ACURA,ILX HYBRID,COMPACT,1.5,4,AV7,Z,6.0,5.8,5.9,48,136
3,ACURA,MDX 4WD,SUV - SMALL,3.5,6,AS6,Z,12.7,9.1,11.1,25,255
4,ACURA,RDX AWD,SUV - SMALL,3.5,6,AS6,Z,12.1,8.7,10.6,27,244
...,...,...,...,...,...,...,...,...,...,...,...,...
7380,VOLVO,XC40 T5 AWD,SUV - SMALL,2.0,4,AS8,Z,10.7,7.7,9.4,30,219
7381,VOLVO,XC60 T5 AWD,SUV - SMALL,2.0,4,AS8,Z,11.2,8.3,9.9,29,232
7382,VOLVO,XC60 T6 AWD,SUV - SMALL,2.0,4,AS8,Z,11.7,8.6,10.3,27,240
7383,VOLVO,XC90 T5 AWD,SUV - STANDARD,2.0,4,AS8,Z,11.2,8.3,9.9,29,232
7384,VOLVO,XC90 T6 AWD,SUV - STANDARD,2.0,4,AS8,Z,12.2,8.7,10.7,26,248

In [3]:
df.shape

(7385, 12)

In [4]:
df.describe

<bound method NDFrame.describe of        Make        Model   Vehicle Class  Engine Size(L)  Cylinders  \
0     ACURA          ILX         COMPACT             2.0          4
1     ACURA          ILX         COMPACT             2.4          4
2     ACURA   ILX HYBRID         COMPACT             1.5          4
3     ACURA      MDX 4WD     SUV - SMALL             3.5          6
4     ACURA      RDX AWD     SUV - SMALL             3.5          6
...     ...          ...             ...             ...        ...
7380  VOLVO  XC40 T5 AWD     SUV - SMALL             2.0          4
7381  VOLVO  XC60 T5 AWD     SUV - SMALL             2.0          4
7382  VOLVO  XC60 T6 AWD     SUV - SMALL             2.0          4
7383  VOLVO  XC90 T5 AWD  SUV - STANDARD             2.0          4
7384  VOLVO  XC90 T6 AWD  SUV - STANDARD             2.0          4

     Transmission Fuel Type  Fuel Consumption City (L/100 km)  \
0             AS5         Z                               9.9
1              M6         Z                              11.2
2             AV7         Z                               6.0
3             AS6         Z                              12.7
4             AS6         Z                              12.1
...           ...       ...                               ...
7380          AS8         Z                              10.7
7381          AS8         Z                              11.2
7382          AS8         Z                              11.7
7383          AS8         Z                              11.2
7384          AS8         Z                              12.2

      Fuel Consumption Hwy (L/100 km)  Fuel Consumption Comb (L/100 km)  \
0                                 6.7                               8.5
1                                 7.7                               9.6
2                                 5.8                               5.9
3                                 9.1                              11.1
4                                 8.7                              10.6
...                               ...                               ...
7380                              7.7                               9.4
7381                              8.3                               9.9
7382                              8.6                              10.3
7383                              8.3                               9.9
7384                              8.7                              10.7

      Fuel Consumption Comb (mpg)  CO2 Emissions(g/km)
0                              33                  196
1                              29                  221
2                              48                  136
3                              25                  255
4                              27                  244
...                           ...                  ...
7380                           30                  219
7381                           29                  232
7382                           27                  240
7383                           29                  232
7384                           26                  248

[7385 rows x 12 columns]>

In [5]:
df.isnull().sum()

Make                                0
Model                               0
Vehicle Class                       0
Engine Size(L)                      0
Cylinders                           0
Transmission                        0
Fuel Type                           0
Fuel Consumption City (L/100 km)    0
Fuel Consumption Hwy (L/100 km)     0
Fuel Consumption Comb (L/100 km)    0
Fuel Consumption Comb (mpg)         0
CO2 Emissions(g/km)                 0
dtype: int64

In [ ]:
df.info()  #conc. data

<class 'pandas.DataFrame'>
RangeIndex: 7385 entries, 0 to 7384
Data columns (total 12 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Make                              7385 non-null   str
 1   Model                             7385 non-null   str
 2   Vehicle Class                     7385 non-null   str
 3   Engine Size(L)                    7385 non-null   float64
 4   Cylinders                         7385 non-null   int64
 5   Transmission                      7385 non-null   str
 6   Fuel Type                         7385 non-null   str
 7   Fuel Consumption City (L/100 km)  7385 non-null   float64
 8   Fuel Consumption Hwy (L/100 km)   7385 non-null   float64
 9   Fuel Consumption Comb (L/100 km)  7385 non-null   float64
 10  Fuel Consumption Comb (mpg)       7385 non-null   int64
 11  CO2 Emissions(g/km)               7385 non-null   int64
dtypes: float64(4), int64(3), str(5)
memory usage: 692.5 KB

In [7]:
df.drop(['Make','Model', 'Vehicle Class', 'Fuel Consumption City (L/100 km)', 'Fuel Consumption Hwy (L/100 km)', 'Fuel Consumption Comb (L/100 km)', 'Fuel Consumption Comb (mpg)'],axis=1)

      Engine Size(L)  Cylinders Transmission Fuel Type  CO2 Emissions(g/km)
0                2.0          4          AS5         Z                  196
1                2.4          4           M6         Z                  221
2                1.5          4          AV7         Z                  136
3                3.5          6          AS6         Z                  255
4                3.5          6          AS6         Z                  244
...              ...        ...          ...       ...                  ...
7380             2.0          4          AS8         Z                  219
7381             2.0          4          AS8         Z                  232
7382             2.0          4          AS8         Z                  240
7383             2.0          4          AS8         Z                  232
7384             2.0          4          AS8         Z                  248

[7385 rows x 5 columns]

In [8]:
#from sklearn.linear_model import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split

In [9]:
X=df[["Engine Size(L)", "Cylinders"]]
Y=df["CO2 Emissions(g/km)"]
Y

0       196
1       221
2       136
3       255
4       244
       ...
7380    219
7381    232
7382    240
7383    232
7384    248
Name: CO2 Emissions(g/km), Length: 7385, dtype: int64

In [10]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,random_state=42,test_size=.4)
X_test

      Engine Size(L)  Cylinders
7261             3.0          6
4489             4.4          8
1539             6.2          8
3532             5.3          8
6418             4.0          6
...              ...        ...
3002             5.5          8
4434             6.0         12
3529             1.5          4
366              3.5          6
1432             1.4          4

[2954 rows x 2 columns]

In [11]:
model=LinearRegression()
model.fit(X_train,Y_train)

LinearRegression()

In [12]:
Y_predict=model.predict(X_test)
Y_predict

r2_score(Y_test,Y_predict)

0.7303991103699322

In [13]:
import pandas as pd

In [14]:
df=pd.read_csv("Iris.csv")
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [15]:
df.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [16]:
df.info

<bound method DataFrame.info of       Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2
1      2            4.9           3.0            1.4           0.2
2      3            4.7           3.2            1.3           0.2
3      4            4.6           3.1            1.5           0.2
4      5            5.0           3.6            1.4           0.2
..   ...            ...           ...            ...           ...
145  146            6.7           3.0            5.2           2.3
146  147            6.3           2.5            5.0           1.9
147  148            6.5           3.0            5.2           2.0
148  149            6.2           3.4            5.4           2.3
149  150            5.9           3.0            5.1           1.8

            Species
0       Iris-setosa
1       Iris-setosa
2       Iris-setosa
3       Iris-setosa
4       Iris-setosa
..              ...
145  Iris-virginica
146  Iris-virginica
147  Iris-virginica
148  Iris-virginica
149  Iris-virginica

[150 rows x 6 columns]>

In [17]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split

In [18]:
df.columns.to_list()

['Id',
 'SepalLengthCm',
 'SepalWidthCm',
 'PetalLengthCm',
 'PetalWidthCm',
 'Species']

In [19]:
X=df[["SepalLengthCm", "SepalWidthCm","PetalLengthCm","PetalWidthCm"]]
Y=df["Species"]
Y

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: str

In [20]:
model = LogisticRegression()
model.fit(X_train,Y_train)

c:\Users\hp\Desktop\krmu\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [21]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,random_state=42, test_size=.2)

In [23]:
#Y_predict = model.predict(X_test)
#Y_predict

In [25]:
#data = [[ 4.9,3.0,1.4,0.2]]
#model.predict(data)